### ISSUE TITLE
Download button doesn't work

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/dapperdesktop#2]
@Mamaduka It looks like in Chrome on Win10 the download button activates but I can't click on any of the links.

In Firefox on MacOS pushing the button does nothing.

It works fine on Chrome on MacOS. 

So strange. Can you have a look and push a quick fix?

**Comment by Mamaduka** [comment]
@nickhamze I was using CSS `:focus` click hack to display popover. Looks like it doesn't work in some browsers anymore.

I added a small JS script that will handle click logic and should fix the issue.

Please test and let me know if this is good for a small release.

**Comment by nickhamze** [comment]
It's working well for me. I think it's ready for the release.

**Comment by Mamaduka** [comment]
Released a new version and it's currently deploying to WP.org
