### ISSUE TITLE
The button styling must have changed

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/dapperdesktop#3]
@Mamaduka The button looks a bit weird, something must have changed. 
<img width="670" alt="Screen Shot 2020-03-25 at 5 26 46 PM" src="https://user-images.githubusercontent.com/158918/77591447-fa927d00-6ebd-11ea-8e51-3d0374ce2eae.png">

**Comment by Mamaduka** [comment]
@nickhamze fixed the issue. Should I bump "Tested up to" WP version as well and deploy a new release?

**Comment by nickhamze** [comment]
@Mamaduka yes, please
